server {
    # Nginx port 80 par Web HTTP traffic listen karega
    listen 80;

    # Container ke andar jahan aapki Frontend (HTML/CSS/JS) files store hain
    root /usr/share/nginx/html;

    # Default file jo website open hone par sabse pehle load hogi
    index index.html;

    # Frontend Routing Block: Handles static web pages & single page application routes
    location / {
        # Pehle check karta hai file ($uri) ya folder ($uri/) exist karta hai ya nahi,
        # agar nahi milta toh index.html par fallback kar deta hai.
        try_files $uri $uri/ /index.html;
    }

    # Reverse Proxy Block: Handlers all API requests starting with /api/
    location /api/ {
        # Browser se aane wali request ko internal Flask backend service ko forward kar deta hai
        proxy_pass http://backend:5000;

        # Client details ko preserve karne ke liye HTTP headers set karta hai
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}